package com.Devas.BackendPrescription.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

@Document // saved as doctors collection in mongodb
public class Doctor {

  @Id
  private String id;  //autogenerated id

  @NotBlank(message = "username cannot be empty")
  @Indexed(unique = true)
  @Size(max = 10)
  private String username;          //username used for login

  @NotBlank(message = "name cannot be empty")
  @Size(max=20)
  private String name;             // Name of the doctor

  @NotBlank(message = "Mobile no cannot be empty")
  @Digits(integer = 12, fraction = 0)
  private String mobile;              //mobile number including country code example 91 - india

  @NotBlank(message = "email cannot be empty")
  @Indexed(unique = true)
  @Email
  private String email;

  @NotBlank
  private String address;
/*
  private String idProof;                  // ID proof name example - driving license
  private String idProofNumber;            // ID proof reference number or ID number of the above asked ID Proof
*/
  @NotBlank(message = "password cannot be empty")
  @Size(min=6)
  private String password;                 // Password used for login

  //below are getters and setters for the above data

  public String getId() {
    return id;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  // used post request in registration

  public Doctor(String username, String name, String mobile, String email, String password, String address) {
    this.address = address;
    this.username = username;
    this.name = name;
    this.mobile = mobile;
    this.email = email;
    this.password = password;
  }
}
